# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 13:27
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import j29.generic.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique=True)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('live', models.BooleanField(default=True, help_text=b'Only live sites with dates today or in the past will be shown.')),
            ],
            options={
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_and_time', models.DateTimeField()),
                ('full_price_ticket_cost', j29.generic.fields.DecimalCurrencyField(decimal_places=2, help_text=b'Enter an integer value, or a value in decimal currency, e.g. 9.99; 50.00.', max_digits=10)),
                ('booking_link', models.URLField(blank=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['date_and_time'],
            },
        ),
        migrations.CreateModel(
            name='ConcessionaryTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ticket_cost', j29.generic.fields.DecimalCurrencyField(decimal_places=2, help_text=b'Enter an integer value, or a value in decimal currency, e.g. 9.99; 50.00.', max_digits=10)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Concert')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=b'conductors')),
                ('weight', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=b'image_library')),
            ],
            options={
                'ordering': ['-upload_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=128)),
                ('address_line_2', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('postcode', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('role', models.CharField(help_text=b'e.g. "conductor" or "trumpet"', max_length=128)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Concert')),
            ],
            options={
                'ordering': ['weight'],
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('composer', models.CharField(max_length=128)),
                ('weight', models.PositiveIntegerField(default=0)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Concert')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_the_orchestra', models.TextField()),
                ('quote_text', models.CharField(max_length=256)),
                ('quote_source', models.CharField(max_length=128)),
                ('facebook_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('season_name', models.CharField(max_length=128)),
                ('about_image_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_image_1', to='hallamsinfonia.Image')),
                ('about_image_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_image_2', to='hallamsinfonia.Image')),
                ('about_image_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_image_3', to='hallamsinfonia.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Image'),
        ),
        migrations.AddField(
            model_name='concert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Location'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Image'),
        ),
    ]
