# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from hallamsinfonia.models import Season, Concert
from datetime import datetime


def forwards(apps, schema_editor):
    # Custom code to add the default season if concerts already exist
    s = Season(title='Default Season', start_date=datetime(2008, 1, 1))
    s.save()


def reverse(apps, schema_editor):
    # Custom code to delete seasons
    Season.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('hallamsinfonia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(editable=False)),
                ('start_date', models.DateField(help_text='Not displayed - used for sorting only')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='setting',
            name='season_name',
        ),
        migrations.RunPython(forwards, reverse),
    ]
