# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from hallamsinfonia.models import Season
from datetime import datetime


def forwards(apps, schema_editor):
    # Custom code to add the default season
    s = Season(title='Default Season', start_date=datetime.now(), pk=1)
    s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hallamsinfonia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('start_date', models.DateField(help_text=b'Not displayed - used for sorting only')),
            ],
        ),
        migrations.RemoveField(
            model_name='setting',
            name='season_name',
        ),
        migrations.RunPython(forwards, hints={'target_db': 'default'}),
        migrations.AddField(
            model_name='concert',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Season'),
            preserve_default=False,
        ),
    ]
