# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hallamsinfonia.models


def default_season():
    """ Migration aid - get the first available season as the default """
    return hallamsinfonia.models.Season.objects.first().pk


class Migration(migrations.Migration):

    dependencies = [
        ('hallamsinfonia', '0002_auto_20160322_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='season',
            field=models.ForeignKey(
                default=default_season,
                on_delete=django.db.models.deletion.CASCADE,
                to='hallamsinfonia.Season'
            ),
        ),
    ]
