# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallamsinfonia', '0002_auto_20160320_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(default='Default', editable=False),
            preserve_default=False,
        ),
    ]
