# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-14 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hallamsinfonia', '0003_concert_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallamsinfonia.Season'),
        ),
    ]
